# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_window_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QFrame, QGraphicsDropShadowEffect, QGraphicsBlurEffect, QGraphicsColorizeEffect


class Ui_Second_Window(object):
    def setupUi(self, Second_Window):
        Second_Window.setObjectName("Second_Window")
        Second_Window.resize(672, 480)
        Second_Window.setFixedSize(QtCore.QSize(640, 480))

        self.centralwidget = QtWidgets.QWidget(Second_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.headingframe = QtWidgets.QFrame(self.centralwidget)
        self.headingframe.setMinimumSize(QtCore.QSize(0, 90))
        self.headingframe.setMaximumSize(QtCore.QSize(16777215, 90))
        self.headingframe.setBaseSize(QtCore.QSize(0, 90))
        self.headingframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headingframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headingframe.setObjectName("headingframe")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headingframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setAlignment(Qt.AlignHCenter)

        # RESULT LABEL
        self.label = QtWidgets.QLabel(self.headingframe)
        self.label.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

# line under Result
        self.underline = QtWidgets.QLabel(self.headingframe)
        self.underline.setText(" ")
        self.underline.setGeometry(257, 63, 100, 3)
        self.underline.setObjectName("Underline_label")

        self.horizontalLayout.addWidget(
            self.label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.headingframe)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setFixedSize(600, 350)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontal_layout_of_frame_2")

        # tableWiidget
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(115, 30, 400, 270))
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.setColumnCount(2)

        # row_count_in_second_window
        self.tableWidget.setRowCount(0)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(66, 4, 220))
        item.setForeground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(66, 4, 220))
        item.setForeground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)

        self.verticalLayout.addWidget(self.frame_2)
        Second_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Second_Window)
        QtCore.QMetaObject.connectSlotsByName(Second_Window)

    def retranslateUi(self, Second_Window):
        _translate = QtCore.QCoreApplication.translate
        Second_Window.setWindowTitle(
            _translate("Second_Window", "COUNT TABLE"))
        self.label.setText(_translate("Second_Window", "RESULT"))
        item = self.tableWidget.horizontalHeaderItem(0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPixelSize(18)
        item.setFont(font)

        item.setText(_translate("Second_Window", "Candidates"))
        item = self.tableWidget.horizontalHeaderItem(1)

        font = QtGui.QFont()
        font.setBold(True)
        font.setPixelSize(18)
        item.setFont(font)

        item.setText(_translate("Second_Window", "Votes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_Window = QtWidgets.QMainWindow()
    ui = Ui_Second_Window()
    ui.setupUi(Second_Window)

    with open("second.css", "r") as file:
        app.setStyleSheet(file.read())
    Second_Window.show()
    sys.exit(app.exec_())
